Repository sch1zk/Imperial-Space-SS14, pull requests merged in 2023-01, with the labels that each got.

#23 Update spiderlings
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/_Imperial/Entities/Mobs/NPCs/tarantula.yml
Labels: No C#

#25 Add demon
  Resources/Locale/en-US/ss14-ru/prototypes/_imperial/entities/mobs/player/demon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/demon.ftl
  Resources/Prototypes/_Imperial/Entities/Mobs/Player/demon.yml
  Resources/Textures/Mobs/Ghosts/demon.rsi/dead.png
  Resources/Textures/Mobs/Ghosts/demon.rsi/demon.png
  Resources/Textures/Mobs/Ghosts/demon.rsi/icon.png
  Resources/Textures/Mobs/Ghosts/demon.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#30 Ручка Sybercun
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/paper.ftl
  Resources/Prototypes/Catalog/VendingMachines/Inventories/games.yml
  Resources/Prototypes/Entities/Objects/Misc/paper.yml
  Resources/Prototypes/_Imperial/Catalog/games_catalog.yml
Labels: Changes: Localization, No C#

#19 Add cult sword
  Resources/Locale/en-US/ss14-ru/prototypes/_imperial/entities/objects/weapons/cult_sword.fnl
  Resources/Locale/ru-RU/ss14-ru/prototypes/_imperial/entities/objects/weapons/cult_sword.ftl
  Resources/Prototypes/_Imperial/Entities/Objects/Weapons/cult_sword.yml
  Resources/Textures/Objects/Weapons/Melee/cult_sword.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Melee/cult_sword.rsi/icon.png
  Resources/Textures/Objects/Weapons/Melee/cult_sword.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/cult_sword.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Melee/cult_sword.rsi/meta.json
Labels: Changes: Sprites, Changes: UI, Changes: Localization, Changes: Map

#24 Update monkay
  Resources/Prototypes/Body/Parts/animal.yml
  Resources/Prototypes/Body/Prototypes/primate.yml
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/InventoryTemplates/monkey_inventory_template.yml
Labels: No C#

#32 Новые цели Станции
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Prototypes/Corvax/Objectives/goals.yml
Labels: Changes: Localization, No C#

#39 Карты карты карты
  Resources/Maps/infiltrator.yml
  Resources/Maps/mooseImperial.yml
  Resources/Maps/nukieplanet.yml
Labels: Changes: Map, No C#

#43 QoL update
  Resources/Changelog/ChangelogImperial.yml
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/backpacks/startergear/backpack.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/humanoid.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Structures/Machines/fax_machine.yml
  Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
Labels: Changes: Localization, No C#
